
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.elmalrod.boxworld.AnalizadoresXML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIPO_END = 10;
  public static final int LINE_START = 11;
  public static final int LEXEMA_END = 8;
  public static final int ERROR_START = 3;
  public static final int LINE_END = 12;
  public static final int DESCRIPCION_END = 16;
  public static final int COLUMN_END = 14;
  public static final int numero = 17;
  public static final int TIPO_START = 9;
  public static final int ERRORS_START = 5;
  public static final int EOF = 0;
  public static final int ERRORS_END = 6;
  public static final int LEXEMA_START = 7;
  public static final int DESCRIPCION_START = 15;
  public static final int error = 1;
  public static final int TEXT = 2;
  public static final int ERROR_END = 4;
  public static final int COLUMN_START = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEXT",
  "ERROR_START",
  "ERROR_END",
  "ERRORS_START",
  "ERRORS_END",
  "LEXEMA_START",
  "LEXEMA_END",
  "TIPO_START",
  "TIPO_END",
  "LINE_START",
  "LINE_END",
  "COLUMN_START",
  "COLUMN_END",
  "DESCRIPCION_START",
  "DESCRIPCION_END",
  "numero"
  };
}

