
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.elmalrod.boxworld.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parc = 16;
  public static final int para = 15;
  public static final int UP = 4;
  public static final int numero = 2;
  public static final int por = 13;
  public static final int FLOOR = 9;
  public static final int CEIL = 10;
  public static final int RIGHT = 7;
  public static final int menos = 12;
  public static final int LEFT = 6;
  public static final int div = 14;
  public static final int EOF = 0;
  public static final int puntocoma = 17;
  public static final int PUSH = 8;
  public static final int error = 1;
  public static final int DOWN = 5;
  public static final int mas = 11;
  public static final int operacion = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero",
  "operacion",
  "UP",
  "DOWN",
  "LEFT",
  "RIGHT",
  "PUSH",
  "FLOOR",
  "CEIL",
  "mas",
  "menos",
  "por",
  "div",
  "para",
  "parc",
  "puntocoma"
  };
}

