
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comilla = 15;
  public static final int BRICK_COLOR = 24;
  public static final int TARGETS = 33;
  public static final int coma = 14;
  public static final int BOX_COLOR = 21;
  public static final int TARGET_COLOR = 23;
  public static final int FLOOR = 39;
  public static final int ROWS = 18;
  public static final int CONFIG = 20;
  public static final int llaveb = 9;
  public static final int TYPE = 31;
  public static final int BOX_ON_TARGET_COLOR = 22;
  public static final int llavea = 8;
  public static final int BOARD = 28;
  public static final int numero = 37;
  public static final int HALL = 36;
  public static final int menos = 3;
  public static final int HALL_COLOR = 25;
  public static final int BRICK = 35;
  public static final int EOF = 0;
  public static final int PLAYER = 34;
  public static final int parc = 7;
  public static final int mas = 2;
  public static final int para = 6;
  public static final int error = 1;
  public static final int corb = 11;
  public static final int cora = 10;
  public static final int por = 4;
  public static final int dospuntos = 12;
  public static final int NAME = 17;
  public static final int POSY = 30;
  public static final int POSX = 29;
  public static final int COLS = 19;
  public static final int operacion = 38;
  public static final int BOXES = 32;
  public static final int CEIL = 40;
  public static final int div = 5;
  public static final int UNDEFINED_COLOR = 26;
  public static final int HEX_COLOR = 16;
  public static final int PLAYER_COLOR = 27;
  public static final int cadena = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "para",
  "parc",
  "llavea",
  "llaveb",
  "cora",
  "corb",
  "dospuntos",
  "cadena",
  "coma",
  "comilla",
  "HEX_COLOR",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "BOARD",
  "POSX",
  "POSY",
  "TYPE",
  "BOXES",
  "TARGETS",
  "PLAYER",
  "BRICK",
  "HALL",
  "numero",
  "operacion",
  "FLOOR",
  "CEIL"
  };
}

